name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "cd /path/to/your/app && git pull origin main && docker-compose down && docker-compose up --build -d"
        rm -f private_key.pem
